#.travis.yml

language: node_js
node_js:
  - "7.8"

branches:
  only:
      - master
      - refsfor

before_script:
#  - npm install -g firebase-tools
  - npm install

script:
  - npm test

after_success:

notifications:
  email:
      on_failure: change
      on_success: change